name: Build and Test our Brain Teasers
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our code
        uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore Packages
        run: dotnet restore
      - name: Build our code
        run: dotnet build
      - run: dotnet test
